# Generated by Django 4.2.3 on 2024-05-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0002_structuremodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mymodel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="structuremodel",
            name="created_at",
        ),
    ]
