# Generated by Django 4.2.3 on 2024-05-06 09:34

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0003_remove_mymodel_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
            ],
            bases=(models.Model, crud.models.Utility),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnic", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("area", models.FloatField(help_text="Area in square meters")),
                ("contract_number", models.CharField(max_length=20)),
                (
                    "monthly_consumption_units",
                    models.IntegerField(help_text="Monthly consumption in units"),
                ),
            ],
            bases=(models.Model, crud.models.Utility),
        ),
        migrations.CreateModel(
            name="Inverter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("choice", models.CharField(max_length=100)),
                ("capacity", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
            bases=(models.Model, crud.models.Utility),
        ),
        migrations.CreateModel(
            name="NetMetering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phase_type", models.CharField(max_length=50)),
            ],
            bases=(models.Model, crud.models.Utility),
        ),
        migrations.CreateModel(
            name="SolarPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("capacity", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
            bases=(models.Model, crud.models.Utility),
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("l2", models.CharField(blank=True, max_length=100, null=True)),
                ("l3", models.CharField(blank=True, max_length=100, null=True)),
                ("h_beam", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("price", models.FloatField()),
            ],
            bases=(models.Model, crud.models.Utility),
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.DeleteModel(
            name="StructureModel",
        ),
    ]
