# Generated by Django 4.2.3 on 2024-05-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0004_cabling_client_inverter_netmetering_solarpanel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cabling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crud.cabling"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crud.client"
                    ),
                ),
                (
                    "inverter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crud.inverter"
                    ),
                ),
                (
                    "net_metering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crud.netmetering",
                    ),
                ),
                (
                    "solar_panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crud.solarpanel",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crud.structure"
                    ),
                ),
            ],
        ),
    ]
