# Generated by Django 4.2.3 on 2024-05-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0005_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="h_beam",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="l2",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="l3",
        ),
        migrations.AddField(
            model_name="cabling",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="netmetering",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="structure",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="inverter",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="cabling",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="crud.cabling"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="crud.client"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="inverter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="crud.inverter"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="net_metering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="crud.netmetering"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="solar_panel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="crud.solarpanel"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="crud.structure"
            ),
        ),
        migrations.AlterField(
            model_name="solarpanel",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solarpanel",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
