# Generated by Django 4.2.3 on 2024-05-17 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0007_invoice_created_at_invoice_status_invoice_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUOTE", "Quote"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("PAID", "paid"),
                ],
                default="QUOTE",
                max_length=15,
            ),
        ),
    ]
