# Generated by Django 4.2.3 on 2024-05-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0008_alter_invoice_created_at_alter_invoice_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cabling",
            old_name="brand",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="inverter",
            old_name="brand",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="client",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="solarpanel",
            old_name="brand",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="structure",
            old_name="type",
            new_name="name",
        ),
    ]
