# Generated by Django 4.2.3 on 2024-06-07 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0011_remove_invoice_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cabling_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cabling_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="invoice",
            name="inverter_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="inverter_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="invoice",
            name="net_metering_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="net_metering_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="invoice",
            name="solar_panel_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="solar_panel_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="invoice",
            name="structure_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="structure_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUOTE", "Quote"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("PAID", "Paid"),
                ],
                default="QUOTE",
                max_length=15,
            ),
        ),
    ]
