# Generated by Django 4.2.3 on 2024-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0014_alter_invoice_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="shipping_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Enter shipping charges.",
                max_digits=15,
            ),
        ),
    ]
