# Generated by Django 4.2.3 on 2024-06-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0015_invoice_shipping_charges"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
