# Generated by Django 4.2.3 on 2024-06-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_rename_contract_number_client_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter amount paid for partially paid invoices.', max_digits=15),
        ),
    ]
