# Generated by Django 4.2.3 on 2024-07-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_invoice_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter total amount.', max_digits=15),
        ),
    ]
