# Generated by Django 4.2.3 on 2024-07-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_batteries_installation_lightningarrestor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='battery_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cabling_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='installation_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='inverter_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lightning_arrestor_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_metering_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='solar_panel_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='structure_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
