# Generated by Django 4.2.3 on 2024-07-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0022_alter_invoice_battery_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='battery_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='battery_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='installation_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='installation_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lightning_arrestor',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lightning_arrestor_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lightning_arrestor_quantity',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cabling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.cabling'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='inverter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.inverter'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_metering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.netmetering'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='solar_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.solarpanel'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.structure'),
        ),
    ]
