# Generated by Django 4.2.3 on 2024-07-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0023_remove_invoice_battery_remove_invoice_battery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.batteries'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='battery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='battery_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.installation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installation_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installation_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lightning_arrestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.lightningarrestor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lightning_arrestor_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lightning_arrestor_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
