# Generated by Django 4.2.3 on 2024-07-30 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0024_invoice_battery_invoice_battery_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiallyPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.invoice')),
            ],
        ),
    ]
