# Generated by Django 4.2.3 on 2024-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0026_expenditures"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="system_capacity",
            field=models.TextField(blank=True, default=0.0, null=True),
        ),
    ]
